### ISSUE TITLE
AttributeError: 'KNGraph' object has no attribute 'mark_output'

### ISSUE THREAD

**Issue by chairman-lu** [mirage-project/mirage#106]
I just try the code in tutorials:
![image](https://github.com/user-attachments/assets/7b25b1e8-37da-4a8b-9146-5e111de3d407)

and got the error:
`AttributeError: 'KNGraph' object has no attribute 'mark_output'`

environment:
cuda 11.8
torch 2.3.1+cu118

**Comment by jiazhihao** [comment]
`mark_output` is a new API introduced in v0.2.1. We are in the process of updating pypi lib. Meanwhile, can you try to install Mirage from source code using `pip install .`

**Comment by chairman-lu** [comment]
OK I tried and fixed the problem, but another error occured.
`AttributeError: module 'mirage' has no attribute 'superoptimize'`
why is that?

**Comment by jiazhihao** [comment]
`superoptimize` is now a function of the `KNGraph` object. This is another API change we made recently.

**Comment by chairman-lu** [comment]
OK, got it
