### ISSUE TITLE
Mirage discovers more mugraphs for the demos after introducing `KNOutputOp`

### ISSUE THREAD

**Issue by jiazhihao** [mirage-project/mirage#111]
After merging the KNOutputOp related changes, it seems Mirage's search algorithm now discovers more valid mugraphs for the modes. E.g., Mirage found 7 valid mugraphs for `demo_rms_norm.py` before these changes and now returns 23 valid mugraphs after the changes. Not sure if this is a bug/inefficiency, or the search now considers a larger space and thus more valid candidates.

**Comment by wmdi** [comment]
I think this is because there were issues with the range-based pruning algorithm. I modified the range propagation for DIV ops in that PR, which might be the reason why we get more mugraphs now.

**Comment by jiazhihao** [comment]
That makes sense. Once we have the visualizer, it would be helpful to look into them and see if there is any duplication.
