### ISSUE TITLE
module 'mirage' has no attribute 'new_graph'

### ISSUE THREAD

**Issue by mert-cemri** [mirage-project/mirage#35]
When I install mirage with pip install ., i cannot access to the classes or methods inside mirage library, as in:
>>> import mirage as mi
>>> graph = mi.new_graph()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mirage' has no attribute 'new_graph'

**Comment by 2niuhe** [comment]
Some of the demos and examples in the current project have not been updated alongside the code and are now outdated.

The new interface should be new_kernel_graph.

You can refer to the original project here:
https://github.com/jiazhihao/attention_superoptimizer.
