### ISSUE TITLE
Memory manager for tensors

### ISSUE THREAD

**Issue by jiazhihao** [mirage-project/mirage#5]
Copied from the previous repo @wmdi:

We want to remove `data_ptr` and `fp_ptr` fields in `DTensor` and instead have a memory manager to provide data addresses via tensor guids. The benefits are: 1) we don't have to handle pointers in the python side; 2) we can support deserialization without allocating memory; 3) it is easier to maintain data consistency for tensors with the same guid.

Specifically, we need to replace `data_ptr` and `fp_ptr` in `DTensor` by two private methods, `void* get_data_ptr()` and `FPType *fp_ptr()`, which call the memory manager to get the data pointers and allocate memory for the tensor if it is not allocated. The memory manager maintains a mapping between tensor guids and data addresses. Given a guid, the memory manager gives the pointer to data of the tensor with the guid.

**Comment by wmdi** [comment]
Closed by #22
