### ISSUE TITLE
Running on catalyst-fleet encounters ptxas error during transpilation

### ISSUE THREAD

**Issue by AMKCode** [mirage-project/mirage#94]
Hi,

I was trying to run mirage on catalyst-fleet. However, running the tutorial .py files results in the following error during transpilation, there are multiple instances of these errors at each run of the tutorial files.

ptxas /tmp/tmpxft_003d825c_00000000-8_test.compute_75.ptx, line 191; error   : Feature 'cp.async' requires .target sm_80 or higher

I resolved this by setting CUDA_VISIBLE_DEVICES=0. This makes sure that the GPU used is the RTX 4090, not the RTX 2070. The compute capability of RTX 2070 is not on par with sm_80, hence it is throwing the error.

**Comment by jiazhihao** [comment]
@AMKCode This is because the transpiler currently require a minimum compute capacity of 80. Can you submit an SCS help tick to request access to the catalyst-cluster, which has A5000 GPUs you can use for development?
